### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by cheirekov** [BatteredBunny/virtualhere-nixos#1]
udo nix run github:BatteredBunny/virtualhere-nixos                                                                                                                                                                                   ─╯
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'vhuit64'
         whose name attribute is located at /nix/store/3pif36ks3f56py4wb1dkq6sh0nkf3ygj-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'text' of derivation 'vhuit64'

         at /nix/store/3pif36ks3f56py4wb1dkq6sh0nkf3ygj-source/pkgs/build-support/trivial-builders/default.nix:103:16:

          102|       ({
          103|         inherit text executable checkPhase allowSubstitutes preferLocalBuild;
             |                ^
          104|         passAsFile = [ "text" ]

       error: libxkbcommon_7 has been removed because it is impacted by security issues and not used in nixpkgs, move to 'libxkbcommon'
Traceback (most recent call last):
  File "/nix/store/vih0hmjibqr9mmnfvw0fzn4p03yc4kpy-nix-alien-0.1.0+git20230715112432/bin/.nix-alien-ld-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/vih0hmjibqr9mmnfvw0fzn4p03yc4kpy-nix-alien-0.1.0+git20230715112432/lib/python3.10/site-packages/nix_alien/nix_ld.py", line 85, in main
    return _impl.main(
  File "/nix/store/vih0hmjibqr9mmnfvw0fzn4p03yc4kpy-nix-alien-0.1.0+git20230715112432/lib/python3.10/site-packages/nix_alien/_impl.py", line 237, in main
    create_fn(
  File "/nix/store/vih0hmjibqr9mmnfvw0fzn4p03yc4kpy-nix-alien-0.1.0+git20230715112432/lib/python3.10/site-packages/nix_alien/nix_ld.py", line 35, in create_nix_ld
    return _impl.create(
  File "/nix/store/vih0hmjibqr9mmnfvw0fzn4p03yc4kpy-nix-alien-0.1.0+git20230715112432/lib/python3.10/site-packages/nix_alien/_impl.py", line 63, in create
    subprocess.run(
  File "/nix/store/9c03r86hcdn43dm3hsgjirifvyzfkhwh-python3-3.10.12/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-build', '--no-out-link', PosixPath('/root/.cache/nix-alien/5e56e505-6f9b-5d4f-a250-ee83dbceab54/nix-ld/default.nix')]' returned non-zero exit status 1.

**Comment by BatteredBunny** [comment]
The error most likely came from the choices made in the initial nix-alien selection, the deps are handpicked now so its no longer an issue.
